name: Vite CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Test secret
        run: echo "secret is available"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Test repository variable
        run: 'echo "Application: ${APP_NAME}"'
        env:
          APP_NAME: ${{ vars.APP_NAME }}

  build:
    needs: lint
    runs-on: ubuntu-latest
    environment: development


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: development variables
        run: |
            echo "AppUrl : $APP_URL"
            echo "Database password is configured"
        env:
            APP_URL: ${{ vars.APP_URL }}
            DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}


    
